db:
  username: ${username.value:my_user}
  password: qwerty
  driver: PostgresDriver
  url: postgres:5439
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
#  массив данных
  pools:
    - size: 12
      timeout: 10
    - size: 15
      timeout: 10
    - size: 20
      timeout: 5
  properties:
    first: 123
    second: 567
    third: test

logging:
  level:
    #выводим только WARN и выше
    root: INFO
    # INFO для логгера из ConnectionPool
    ru.edu.database.pool.ConnectionPool: INFO
    # INFO для логгера из пакета
    ru.edu.database.pool: INFO
  file:
    name: my_log.log
#    в корень проекта
    path: /

spring:
#  минимальные настройки для jpa
  datasource:
    url: jdbc:postgresql://localhost:5439/db_dmdev_spring
    username: user
    password: qwerty
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      # опциональные настройки для hibernate
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate