db:
  username: ${username.value:my_user}
  password: qwerty
  driver: PostgresDriver
  url: postgres:5439
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 10
#  массив данных
  pools:
    - size: 12
      timeout: 10
    - size: 15
      timeout: 10
    - size: 20
      timeout: 5
  properties:
    first: 123
    second: 567
    third: test

logging:
  level:
    #выводим только WARN и выше
    root: WARN
    # INFO для логгера из ConnectionPool
    ru.edu.database.pool.ConnectionPool: INFO
    # INFO для логгера из пакета
    ru.edu.database.pool: INFO