version: "3.9"
services:
  postgres:
    container_name: db_dmdev_spring
    image: postgres:14
    environment:
      POSTGRES_DB: "db_dmdev_spring"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5439:5432"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
